export const SERVICES = [
  { id: 1, name: 'Haircut & Style', icon: '✂️', category: 'hair' },
  { id: 2, name: 'Color & Highlights', icon: '🎨', category: 'hair' },
  { id: 3, name: 'Balayage', icon: '✨', category: 'hair' },
  { id: 4, name: 'Blowout', icon: '💨', category: 'hair' },
  { id: 5, name: 'Braids & Locs', icon: '🌿', category: 'hair' },
  { id: 6, name: 'Natural Hair', icon: '🌸', category: 'hair' },
  { id: 7, name: 'Facials', icon: '🧖', category: 'skin' },
  { id: 8, name: 'Waxing', icon: '🌙', category: 'skin' },
  { id: 9, name: 'Lashes', icon: '👁️', category: 'beauty' },
  { id: 10, name: 'Brows', icon: '🦋', category: 'beauty' },
  { id: 11, name: 'Nails', icon: '💅', category: 'nails' },
  { id: 12, name: 'Massage', icon: '🤲', category: 'wellness' },
  { id: 13, name: 'Barbering', icon: '🪒', category: 'hair' },
  { id: 14, name: 'Makeup', icon: '💄', category: 'beauty' },
]

export const PROFESSIONALS = [
  {
    id: 'p1',
    name: 'Ariana Cole',
    businessName: 'Ariana Beauty Studio',
    specialty: 'Color Specialist & Balayage Artist',
    location: 'Arlington, TX',
    suite: '32',
    rating: 4.9,
    reviewCount: 312,
    price: '$85+',
    nextAvailable: 'Today 3:00 PM',
    services: ['Color & Highlights', 'Balayage', 'Haircut & Style'],
    tags: ['Top Rated', 'Trending'],
    coverColor: 'from-purple-600 to-pink-500',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=ariana&backgroundColor=b6e3f4',
    bio: 'Award-winning colorist specializing in balayage and lived-in color. 8 years experience transforming hair.',
    portfolio: ['#f9a8d4', '#c084fc', '#818cf8', '#f472b6'],
    verified: true,
  },
  {
    id: 'p2',
    name: 'Marcus Wright',
    businessName: 'Wright Cut Barbershop',
    specialty: 'Master Barber & Fade Specialist',
    location: 'Arlington, TX',
    suite: '15',
    rating: 4.8,
    reviewCount: 541,
    price: '$45+',
    nextAvailable: 'Today 5:30 PM',
    services: ['Barbering', 'Haircut & Style'],
    tags: ['Top Rated', 'Fast Response'],
    coverColor: 'from-blue-600 to-indigo-500',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=marcus&backgroundColor=c0aede',
    bio: 'Master barber with 12 years crafting precision cuts. Known for clean fades and creative designs.',
    portfolio: ['#60a5fa', '#818cf8', '#a78bfa', '#93c5fd'],
    verified: true,
  },
  {
    id: 'p3',
    name: 'Destiny Simmons',
    businessName: 'Glow + Flow by Destiny',
    specialty: 'Natural Hair & Locs Expert',
    location: 'Arlington, TX',
    suite: '7',
    rating: 5.0,
    reviewCount: 189,
    price: '$65+',
    nextAvailable: 'Tomorrow 10:00 AM',
    services: ['Natural Hair', 'Braids & Locs'],
    tags: ['Top Rated', 'New'],
    coverColor: 'from-emerald-500 to-teal-600',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=destiny&backgroundColor=b6e3f4',
    bio: 'Natural hair specialist celebrating textured beauty. Certified in locs, braiding, and protective styles.',
    portfolio: ['#6ee7b7', '#34d399', '#10b981', '#a7f3d0'],
    verified: true,
  },
  {
    id: 'p4',
    name: 'Sara Martinez',
    businessName: 'SaraJune Spa Suite',
    specialty: 'Esthetician & Lash Artist',
    location: 'Arlington, TX',
    suite: '1',
    rating: 4.9,
    reviewCount: 427,
    price: '$55+',
    nextAvailable: 'Today 6:00 PM',
    services: ['Facials', 'Lashes', 'Waxing'],
    tags: ['Fan Favorite'],
    coverColor: 'from-rose-500 to-pink-600',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=sara&backgroundColor=ffd5dc',
    bio: 'Licensed esthetician and certified lash artist. Skincare obsessed with a gentle touch.',
    portfolio: ['#fda4af', '#fb7185', '#f43f5e', '#fecdd3'],
    verified: true,
  },
  {
    id: 'p5',
    name: 'Tammy Chen',
    businessName: 'Tammy Nails & More',
    specialty: 'Nail Technician & Nail Artist',
    location: 'Arlington, TX',
    suite: '18',
    rating: 4.7,
    reviewCount: 298,
    price: '$35+',
    nextAvailable: 'Tomorrow 2:00 PM',
    services: ['Nails'],
    tags: ['Trending'],
    coverColor: 'from-amber-500 to-orange-500',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=tammy&backgroundColor=ffdfbf',
    bio: 'Nail artist bringing creativity to every set. Gel, acrylic, nail art — you dream it, I create it.',
    portfolio: ['#fcd34d', '#fb923c', '#f97316', '#fef3c7'],
    verified: false,
  },
  {
    id: 'p6',
    name: 'Venita Jackson',
    businessName: 'Venita Wellness Studio',
    specialty: 'Massage Therapist & Reiki',
    location: 'Arlington, TX',
    suite: '6',
    rating: 5.0,
    reviewCount: 156,
    price: '$90+',
    nextAvailable: 'Today 4:00 PM',
    services: ['Massage'],
    tags: ['Top Rated', 'Premium'],
    coverColor: 'from-violet-500 to-purple-600',
    avatar: 'https://api.dicebear.com/7.x/personas/svg?seed=venita&backgroundColor=d8b4fe',
    bio: 'Licensed massage therapist specializing in deep tissue, Swedish, and energy healing modalities.',
    portfolio: ['#c4b5fd', '#a78bfa', '#8b5cf6', '#ede9fe'],
    verified: true,
  },
]

export const REVIEWS = [
  { id: 1, author: 'Jessica M.', rating: 5, text: 'Ariana is literally a hair wizard. My balayage looks like I stepped out of a magazine!', professionalId: 'p1', date: '2 days ago', avatar: 'J' },
  { id: 2, author: 'Kevin T.', rating: 5, text: 'Marcus gave me the cleanest fade of my life. Will not go anywhere else.', professionalId: 'p2', date: '1 week ago', avatar: 'K' },
  { id: 3, author: 'Aaliyah B.', rating: 5, text: 'Destiny understands natural hair like no one else. My locs have never looked better.', professionalId: 'p3', date: '3 days ago', avatar: 'A' },
  { id: 4, author: 'Michael R.', rating: 5, text: 'The AI booking is SO convenient. Booked a cut in literally 30 seconds at midnight.', professionalId: 'p2', date: '5 days ago', avatar: 'M' },
]

export const STATS = [
  { value: '21,000+', label: 'Beauty Professionals' },
  { value: '1M+', label: 'Happy Clients' },
  { value: '162M', label: 'Appointments Booked' },
  { value: '4.9★', label: 'Average Rating' },
]

export const TIME_SLOTS = [
  '9:00 AM', '9:30 AM', '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '12:00 PM', '12:30 PM', '1:00 PM', '1:30 PM', '2:00 PM', '2:30 PM',
  '3:00 PM', '3:30 PM', '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM',
  '6:00 PM', '6:30 PM', '7:00 PM',
]

export const TESTIMONIALS = [
  {
    text: "I used to lose 3+ clients a week to missed calls. With the AI receptionist, I haven't missed a booking in 6 months.",
    author: 'Ariana Cole',
    role: 'Color Specialist',
    metric: '+$2,400/mo revenue',
    avatar: 'A',
  },
  {
    text: "My clients love being able to book at midnight. Half my bookings now come in after hours.",
    author: 'Marcus Wright',
    role: 'Master Barber',
    metric: '+47% new clients',
    avatar: 'M',
  },
  {
    text: "The automated reminders alone cut my no-show rate from 22% to under 5%. Game changer.",
    author: 'Sara Martinez',
    role: 'Esthetician',
    metric: '17% fewer no-shows',
    avatar: 'S',
  },
]
